-- MySQL Script generated by MySQL Workbench
-- Fri Oct  6 20:42:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agiotagem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agiotagem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agiotagem` DEFAULT CHARACTER SET utf8 ;
USE `agiotagem` ;

-- -----------------------------------------------------
-- Table `agiotagem`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agiotagem`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(90) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `foto` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agiotagem`.`destinatario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agiotagem`.`destinatario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `pix` VARCHAR(45) NULL,
  `credito` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_destinatario_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_destinatario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `agiotagem`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agiotagem`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agiotagem`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `icon_svg` LONGTEXT NULL,
  `cor` VARCHAR(45) NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categoria_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_categoria_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `agiotagem`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agiotagem`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agiotagem`.`emprestimo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NULL,
  `valor` FLOAT NOT NULL,
  `numeroparcelas` INT NOT NULL,
  `valorparcela` FLOAT NOT NULL,
  `parcelainicial` DATE NOT NULL,
  `ativo` TINYINT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `destinatario_id` INT NULL,
  `categoria_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_emprestimo_usuarios_idx` (`usuarios_id` ASC),
  INDEX `fk_emprestimo_destinatario1_idx` (`destinatario_id` ASC),
  INDEX `fk_emprestimo_categoria1_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_emprestimo_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `agiotagem`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_destinatario1`
    FOREIGN KEY (`destinatario_id`)
    REFERENCES `agiotagem`.`destinatario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `agiotagem`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agiotagem`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agiotagem`.`Pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `parcela` INT NOT NULL,
  `observacao` VARCHAR(45) NULL,
  `metodo` VARCHAR(45) NULL,
  `comprovante` LONGTEXT NULL,
  `usuario_id` INT NOT NULL,
  `emprestimo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pagamento_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_Pagamento_emprestimo1_idx` (`emprestimo_id` ASC),
  CONSTRAINT `fk_Pagamento_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `agiotagem`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagamento_emprestimo1`
    FOREIGN KEY (`emprestimo_id`)
    REFERENCES `agiotagem`.`emprestimo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
