-- MySQL Script generated by MySQL Workbench
-- Wed Oct  4 20:47:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Agiotagem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Agiotagem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Agiotagem` DEFAULT CHARACTER SET utf8 ;
USE `Agiotagem` ;

-- -----------------------------------------------------
-- Table `Agiotagem`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agiotagem`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(90) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agiotagem`.`destinatario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agiotagem`.`destinatario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `pix` VARCHAR(45) NOT NULL,
  `credito` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Agiotagem`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Agiotagem`.`emprestimo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NULL,
  `valor` FLOAT NOT NULL,
  `numeroparcelas` INT NOT NULL,
  `valorparcela` FLOAT NOT NULL,
  `parcelainicial` DATE NOT NULL,
  `parcelafinal` DATE NOT NULL,
  `ativo` TINYINT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `destinatario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_emprestimo_usuarios_idx` (`usuarios_id` ASC),
  INDEX `fk_emprestimo_destinatario1_idx` (`destinatario_id` ASC),
  CONSTRAINT `fk_emprestimo_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `Agiotagem`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_destinatario1`
    FOREIGN KEY (`destinatario_id`)
    REFERENCES `Agiotagem`.`destinatario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
